// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Form.DAL.Entities;

public partial class Qry201ListOfAccount
{
    public string MasterGroupId { get; set; }

    public string MasterGroup { get; set; }

    public string AccountGroupId { get; set; }

    public string AccountGroup { get; set; }

    public string AccountId { get; set; }

    public string AccountHead { get; set; }

    public bool IsRestricted { get; set; }

    public bool? IsUseInSales { get; set; }

    public bool? IsUsedInPurchase { get; set; }

    public bool? IsProfitLossAccount { get; set; }

    public bool? IsBalanceSheetAccount { get; set; }

    public bool IsMaintainBillByBill { get; set; }

    public bool IsUseInReconciliation { get; set; }

    public string AccountHeadArabic { get; set; }

    public bool IsSalaryPayable { get; set; }

    public string Expr1 { get; set; }

    public string ReferenceNo { get; set; }

    public bool IsLedgerObselete { get; set; }
}