// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Form.DAL.Entities;

public partial class Tbl201VoucherEntry
{
    public long VoucherEntryNo { get; set; }

    public string VoucherNo { get; set; }

    public string AccountHead { get; set; }

    public decimal? VoucherAmount { get; set; }

    public string DrCr { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string EntryNarration { get; set; }

    public string SysRemarks { get; set; }

    public DateTime? BankClearedOn { get; set; }

    public string ReconciliationRemarks { get; set; }

    public string ExpenseClaimRefNo { get; set; }

    public string CostAllocatedFromClaim { get; set; }

    public long? DuplicatedEntryNo { get; set; }

    public string EmpCostAllocFromClaim { get; set; }

    public string PropertyCostAllocFromClaim { get; set; }

    public byte? PayrollAdditionId { get; set; }

    public string PaymentStatus { get; set; }

    public string FinalStatus { get; set; }

    public string SupplierVoucherNo { get; set; }

    public long? JournalChildNo { get; set; }
}