// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Form.DAL.Entities;

public partial class Tbl201VoucherMaster
{
    public string VoucherNo { get; set; }

    public DateTime VoucherDate { get; set; }

    public string VoucherRefNo { get; set; }

    public string VoucherNarration { get; set; }

    public string VoucherEnteredBy { get; set; }

    public DateTime? VoucherEnteredOn { get; set; }

    public string VoucherVerifiedBy { get; set; }

    public DateTime? VoucherVerifiedOn { get; set; }

    public bool? IsVerified { get; set; }

    public string VoucherApprovedBy { get; set; }

    public DateTime? VoucherApprovedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string VoucherType { get; set; }

    public DateTime? VoucherEffectiveDate { get; set; }

    public DateTime? InvoiceSubmittedDate { get; set; }

    public DateTime? InvoiceDueDate { get; set; }

    public short? InvoiceNoOfDays { get; set; }

    public bool? UseSubmittedDate { get; set; }

    public string SalesPersonCode { get; set; }

    public string BillNo { get; set; }

    public DateTime? BillDate { get; set; }

    public string BillPaidTo { get; set; }

    public string BillRemarks { get; set; }

    public string VoucherModifiedBy { get; set; }

    public DateTime? VoucherModifiedOn { get; set; }

    public string AuditVerifiedBy { get; set; }

    public DateTime? AuditVerifiedOn { get; set; }

    public bool? IsAuditVerified { get; set; }

    public string DeliveryNoteNo { get; set; }

    public string CogsInvoiceNo { get; set; }

    public string ReferenceNote { get; set; }

    public string RentalPayslipNo { get; set; }
}